./glideinwms/build/jenkins/run_unittests.sh: line 87: coverage: command not found
TESTING ==========> test_cleanupSupport.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_cleanupSupport.py failed with non zero exit code (127)
TESTING ==========> test_condorExe.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_condorExe.py failed with non zero exit code (127)
TESTING ==========> test_creation_lib_cWDictFile_DictFile.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_creation_lib_cWDictFile_DictFile.py failed with non zero exit code (127)
TESTING ==========> test_creation_lib_cWDictFile_DictFileTwoKeys.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_creation_lib_cWDictFile_DictFileTwoKeys.py failed with non zero exit code (127)
TESTING ==========> test_creation_lib_cWDictFile_DictFileTwoKeys_SubClasses.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_creation_lib_cWDictFile_DictFileTwoKeys_SubClasses.py failed with non zero exit code (127)
TESTING ==========> test_creation_lib_cWDictFile_SHADicts.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_creation_lib_cWDictFile_SHADicts.py failed with non zero exit code (127)
TESTING ==========> test_creation_lib_cWDictFile_validate_node.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_creation_lib_cWDictFile_validate_node.py failed with non zero exit code (127)
TESTING ==========> test_creation_lib_cgWConsts.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_creation_lib_cgWConsts.py failed with non zero exit code (127)
TESTING ==========> test_creation_lib_cgWDictFile.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_creation_lib_cgWDictFile.py failed with non zero exit code (127)
TESTING ==========> test_creation_lib_cgWParamDict.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_creation_lib_cgWParamDict.py failed with non zero exit code (127)
TESTING ==========> test_creation_lib_cgWParams.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_creation_lib_cgWParams.py failed with non zero exit code (127)
TESTING ==========> test_creation_lib_cvWConsts.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_creation_lib_cvWConsts.py failed with non zero exit code (127)
TESTING ==========> test_creation_lib_cvWParamDict.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_creation_lib_cvWParamDict.py failed with non zero exit code (127)
TESTING ==========> test_creation_lib_cvWParams.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_creation_lib_cvWParams.py failed with non zero exit code (127)
TESTING ==========> test_creation_lib_factoryXmlConfig.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_creation_lib_factoryXmlConfig.py failed with non zero exit code (127)
TESTING ==========> test_encodingSupport.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_encodingSupport.py failed with non zero exit code (127)
TESTING ==========> test_factory_glideFactoryConfig.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_factory_glideFactoryConfig.py failed with non zero exit code (127)
TESTING ==========> test_factory_glideFactoryEntry.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_factory_glideFactoryEntry.py failed with non zero exit code (127)
TESTING ==========> test_factory_glideFactoryLib.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_factory_glideFactoryLib.py failed with non zero exit code (127)
TESTING ==========> test_frontend.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_frontend.py failed with non zero exit code (127)
TESTING ==========> test_frontend_element.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_frontend_element.py failed with non zero exit code (127)
TESTING ==========> test_glideFactoryDowntimeLib.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_glideFactoryDowntimeLib.py failed with non zero exit code (127)
TESTING ==========> test_glideinFrontendPlugins.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_glideinFrontendPlugins.py failed with non zero exit code (127)
TESTING ==========> test_lib_encodingSupport.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_lib_encodingSupport.py failed with non zero exit code (127)
TESTING ==========> test_lib_exprParser.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_lib_exprParser.py failed with non zero exit code (127)
TESTING ==========> test_lib_fork.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_lib_fork.py failed with non zero exit code (127)
TESTING ==========> test_lib_pubCrypto.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_lib_pubCrypto.py failed with non zero exit code (127)
TESTING ==========> test_lib_servicePerformance.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_lib_servicePerformance.py failed with non zero exit code (127)
TESTING ==========> test_lib_symCrypto.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_lib_symCrypto.py failed with non zero exit code (127)
TESTING ==========> test_lib_timeConversion.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_lib_timeConversion.py failed with non zero exit code (127)
TESTING ==========> test_lib_x509Support.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_lib_x509Support.py failed with non zero exit code (127)
TESTING ==========> test_lib_xmlParse.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_lib_xmlParse.py failed with non zero exit code (127)
TESTING ==========> test_logSupport.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_logSupport.py failed with non zero exit code (127)
TESTING ==========> test_renew_proxy.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_renew_proxy.py failed with non zero exit code (127)
TESTING ==========> test_tarSupport.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_tarSupport.py failed with non zero exit code (127)
TESTING ==========> test_util.py
./glideinwms/build/jenkins/run_unittests.sh: line 93: coverage: command not found
Wed May 15 21:47:55 UTC 2019 ERROR: test_util.py failed with non zero exit code (127)
./glideinwms/build/jenkins/run_unittests.sh: line 110: coverage: command not found
./glideinwms/build/jenkins/run_unittests.sh: line 111: coverage: command not found
coverage html report failed
no html coverage report generated for v35_22541 on buildservice008.fnal.gov
which: no coverage in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin)
coverage not installed
./glideinwms/build/jenkins/run_unittests.sh: line 117: coverage: command not found
coverage not installed
