-----------------------
Futurize Tests Starting
-----------------------

Python Environment Setup Start


Python Environment Setup Complete


Running on local files in glideinwms subdirectory (LOCAL)


Now running test

find: './creation/add_entry': No such file or directory
find: './unittests/fixtures/frontend/ccvd.fixture': No such file or directory
find: './unittests/fixtures/frontend/pipe_out.do_match': No such file or directory
find: './unittests/fixtures/frontend/pipe_out.iterate_one': No such file or directory
find: './unittests/fixtures/frontend/vofrontend/signatures.sha1': No such file or directory
find: './unittests/fixtures/frontend/web-area/stage/description.e98f4o.cfg': No such file or directory
find: './unittests/fixtures/frontend/web-area/stage/file_list.j4j7WK.lst': No such file or directory
find: './unittests/fixtures/frontend/web-area/stage/group_group1/description.e98f4o.cfg': No such file or directory
find: './unittests/fixtures/frontend/web-area/stage/group_group1/nodes.blacklist': No such file or directory
find: './unittests/fixtures/frontend/web-area/stage/group_group1/signature.j4j84x.sha1': No such file or directory
find: './unittests/fixtures/frontend/web-area/stage/signature.j4j84x.sha1': No such file or directory
find: './unittests/test_creation_lib_cvWCreate.py': No such file or directory
find: './unittests/test_frontend_glideinFrontendConfig.py': No such file or directory
find: './unittests/test_frontend_glideinFrontendElement.py': No such file or directory

There are 2 files that need to be refactored
ERROR: Futurize CRASHED while analyzing branch LOCAL
More than 2 files may need to be refactored


Complete with branch LOCAL (ec:301)


Logs are in /test_dir/output/master/futurize

-----------------------
Futurize Tests Complete - Failed
-----------------------
